"""One-off copy of the local SQLite archive into Postgres.

Run once, when moving from local development to a deployed database:

    python migrate_to_postgres.py --dry-run    # counts only, writes nothing
    python migrate_to_postgres.py

The SQLite file is opened read-only and never deleted, moved, or modified.
If anything goes wrong the original is exactly where it was.

Why the ORM rather than a raw SQL dump: the two engines disagree about
several types this schema uses, and the models already state the correct
answer for each. Copying rows as Python objects lets SQLAlchemy apply the
same conversions it applies in normal operation:

  - booleans are integers 0/1 in SQLite and a real boolean type in Postgres
  - datetimes are ISO *text* in SQLite and a real timestamp in Postgres
  - embeddings are BLOB in SQLite and BYTEA in Postgres

A `.dump`-and-replay would have to reimplement all three by hand, and get
NULL-vs-zero right in the places where this project cares about it most.

Fidelity rules this script exists to protect (see docs/decisions.md):

  - `applied_at` NULL with `application_status='applied'` is real history:
    jobs marked applied before the column existed. It stays NULL. Filling
    in a plausible date would fabricate a record.
  - `retries` NULL means "LangGraph never reported one", not zero.
  - `experience_years_required` NULL means "not stated in the posting",
    not "requires zero years".

Idempotent: rows are upserted on their primary key, so an interrupted run
can simply be repeated. The one exception needing care is
run_agent_metrics, whose integer id is generated by a Postgres sequence -
see _resync_sequences.

Batched deliberately. The obvious implementation - Session.merge() per row -
issues a SELECT *and* an INSERT for every row, which is ~21,000 network
round trips for this archive. Measured against the real Neon instance that
ran at about 1.7 rows/sec (~100 minutes). The batched INSERT ... ON
CONFLICT below sends BATCH_SIZE rows per round trip instead, which is the
difference between a coffee break and a lunch break. Same idempotency,
because ON CONFLICT DO UPDATE is an upsert on the primary key.
"""

import argparse
import sys
from pathlib import Path

from sqlalchemy import create_engine, func, inspect, select, text
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.orm import Session

from db import (
    AnalystResultRow,
    Base,
    CompanyFetchStateRow,
    DEFAULT_DB_PATH,
    JobEmbeddingRow,
    JobPostingRow,
    RunAgentMetricsRow,
    RunMetricsRow,
    database_url,
)

# Ordered so a table never precedes one it references. Nothing here
# declares a foreign key today (run_agent_metrics.run_id is a plain
# indexed column, joined in queries but not constrained), but copying in
# dependency order costs nothing and stops this from becoming a landmine
# the first time a real FK is added.
TABLES = [
    JobPostingRow,
    JobEmbeddingRow,
    AnalystResultRow,
    RunMetricsRow,
    RunAgentMetricsRow,
    CompanyFetchStateRow,
]

BATCH_SIZE = 500


def _column_names(model) -> list[str]:
    return [c.key for c in inspect(model).mapper.column_attrs]


def _row_to_dict(row, columns: list[str]) -> dict:
    return {name: getattr(row, name) for name in columns}


def _count(session: Session, model) -> int:
    return int(session.execute(select(func.count()).select_from(model)).scalar() or 0)


def _upsert_batch(target: Session, model, batch: list[dict]) -> None:
    """One INSERT ... ON CONFLICT DO UPDATE for the whole batch.

    DO UPDATE rather than DO NOTHING so that re-running after a partial
    copy refreshes rows that were written from a since-changed source,
    instead of silently keeping a stale first attempt. The excluded.*
    reference is Postgres's name for "the row this statement tried to
    insert"."""
    pk_columns = {c.name for c in inspect(model).mapper.primary_key}
    statement = pg_insert(model).values(batch)
    updatable = {c: statement.excluded[c] for c in batch[0] if c not in pk_columns}
    target.execute(
        statement.on_conflict_do_update(index_elements=sorted(pk_columns), set_=updatable)
        if updatable
        else statement.on_conflict_do_nothing(index_elements=sorted(pk_columns))
    )
    target.commit()


def _resync_sequences(target: Session) -> list[str]:
    """Advance Postgres's identity sequence past the highest id copied in.

    RunAgentMetricsRow.id is an autoincrement integer. Copying rows with
    explicit ids does NOT advance the sequence backing that column, so the
    next natural insert would reuse id=1 and die on a duplicate key. This
    is the one migration bug that shows up after the migration "succeeds" -
    on the first new run, not during the copy.

    Only models with an autoincrement integer primary key need this; every
    other table here is keyed on a content hash or a name.
    """
    notes = []
    for model in TABLES:
        pk = list(inspect(model).mapper.primary_key)
        if len(pk) != 1:
            continue
        column = pk[0]
        if not isinstance(column.type.python_type, type) or column.type.python_type is not int:
            continue
        table = model.__tablename__
        seq = target.execute(text(f"SELECT pg_get_serial_sequence('{table}', '{column.name}')")).scalar()
        if seq is None:
            continue
        max_id = target.execute(text(f"SELECT COALESCE(MAX({column.name}), 0) FROM {table}")).scalar() or 0
        target.execute(text("SELECT setval(:seq, :value, true)"), {"seq": seq, "value": max(int(max_id), 1)})
        notes.append(f"{table}.{column.name} -> {max_id}")
    target.commit()
    return notes


def migrate(sqlite_path: Path, dry_run: bool = False) -> int:
    url = database_url()
    if url is None:
        print("DATABASE_URL is not set - nothing to migrate into.", file=sys.stderr)
        print("Set it in .env (Neon connection string) and re-run.", file=sys.stderr)
        return 1

    if not sqlite_path.exists():
        print(f"No SQLite database at {sqlite_path}", file=sys.stderr)
        return 1

    # mode=ro is belt-and-braces: this script has no reason to write to the
    # source, and saying so in the URL means a bug can't.
    source_engine = create_engine(f"sqlite:///file:{sqlite_path}?mode=ro&uri=true")
    target_engine = create_engine(url, pool_pre_ping=True)

    print(f"source: {sqlite_path}")
    print(f"target: {target_engine.url.render_as_string(hide_password=True)}")
    print()

    Base.metadata.create_all(target_engine)

    source_counts: dict[str, int] = {}
    target_counts: dict[str, int] = {}

    with Session(source_engine) as source, Session(target_engine) as target:
        for model in TABLES:
            table = model.__tablename__
            columns = _column_names(model)
            total = _count(source, model)
            source_counts[table] = total

            if dry_run:
                print(f"  {table:22} {total:7} rows (dry run - nothing written)")
                continue

            copied = 0
            # yield_per streams from SQLite instead of materializing 10k+
            # ORM objects; the rows are then sent to Postgres in batches
            # rather than one at a time - see the module docstring for the
            # measured reason.
            batch: list[dict] = []
            for row in source.execute(select(model).execution_options(yield_per=BATCH_SIZE)).scalars():
                batch.append(_row_to_dict(row, columns))
                if len(batch) >= BATCH_SIZE:
                    _upsert_batch(target, model, batch)
                    copied += len(batch)
                    batch.clear()
                    print(f"  {table:22} {copied:7}/{total} ...", end="\r")
            if batch:
                _upsert_batch(target, model, batch)
                copied += len(batch)
            print(f"  {table:22} {copied:7} rows copied      ")

    if dry_run:
        print()
        print(f"TOTAL (source): {sum(source_counts.values())} rows")
        return 0

    with Session(target_engine) as target:
        notes = _resync_sequences(target)
        for model in TABLES:
            target_counts[model.__tablename__] = _count(target, model)

    print()
    if notes:
        print("Identity sequences resynced (so the next insert doesn't collide):")
        for note in notes:
            print(f"  {note}")
        print()

    print("VERIFICATION - row counts on both sides")
    print(f"  {'table':22} {'sqlite':>8} {'postgres':>9}   match")
    all_match = True
    for table, expected in source_counts.items():
        actual = target_counts.get(table, 0)
        match = expected == actual
        all_match = all_match and match
        print(f"  {table:22} {expected:8} {actual:9}   {'OK' if match else 'MISMATCH'}")
    total_source = sum(source_counts.values())
    total_target = sum(target_counts.values())
    print(f"  {'TOTAL':22} {total_source:8} {total_target:9}   {'OK' if total_source == total_target else 'MISMATCH'}")

    print()
    _report_fidelity(target_engine)

    print()
    print(f"SQLite file left untouched at {sqlite_path}")
    return 0 if all_match else 2


def _report_fidelity(target_engine) -> None:
    """Re-check the specific NULL-vs-zero distinctions this project treats
    as load-bearing, on the Postgres side, after the copy. A row count
    matching proves nothing about whether a NULL survived as a NULL."""
    with Session(target_engine) as target:
        applied_status = target.execute(
            select(func.count()).select_from(JobPostingRow).where(JobPostingRow.application_status == "applied")
        ).scalar()
        applied_dated = target.execute(
            select(func.count()).select_from(JobPostingRow).where(JobPostingRow.applied_at.isnot(None))
        ).scalar()
        exp_null = target.execute(
            select(func.count())
            .select_from(JobPostingRow)
            .where(JobPostingRow.experience_years_required.is_(None))
        ).scalar()
        retries_null = target.execute(
            select(func.count()).select_from(RunAgentMetricsRow).where(RunAgentMetricsRow.retries.is_(None))
        ).scalar()
        longest_location = target.execute(select(func.max(func.length(JobPostingRow.location)))).scalar()

    print("FIDELITY - the NULLs that must not have become zeros")
    print(f"  application_status='applied'      : {applied_status}")
    print(f"  ...of those, applied_at set       : {applied_dated}  (the rest predate the column - must stay NULL)")
    print(f"  experience_years_required IS NULL : {exp_null}  ('not stated', never 0)")
    print(f"  run_agent_metrics.retries IS NULL : {retries_null}  ('not measured', never 0)")
    print(f"  longest location string           : {longest_location} chars  (Text column - no 300-char cap)")


if __name__ == "__main__":
    sys.stdout.reconfigure(encoding="utf-8")  # same reason as pipeline.py - non-ASCII in real data

    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument(
        "--sqlite-path",
        type=Path,
        default=DEFAULT_DB_PATH,
        help=f"source SQLite database (default: {DEFAULT_DB_PATH})",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="report source row counts and exit without writing anything to Postgres",
    )
    args = parser.parse_args()

    raise SystemExit(migrate(args.sqlite_path, dry_run=args.dry_run))
