/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Ranked survivors, best fit first, with one deliberate exception.
         *
         *     Unscored jobs (the Analyst found no concrete requirements to compare
         *     against) still never receive a fit_score and are never sorted among the
         *     scored ones - their score is not a real comparison. But "unscored" is a
         *     statement about the SKILLS comparison alone. An unscored job that states
         *     an experience requirement the resume meets carries real, independent
         *     evidence, and appending it below every scored job threw that away: a
         *     Cisco posting stating 0 years, met, sat dead last.
         *
         *     So those specific jobs lead the list, still labelled "could not
         *     evaluate" - see app.partition_unscored_by_experience. Ordering here
         *     says "worth your attention", not "scored highest". Everything else is
         *     unchanged: scored jobs by fit descending, remaining unscored jobs last.
         *
         *     include_unscored=False drops all of them, promoted ones included - they
         *     are unscored jobs, and the flag means what it says.
         */
        get: operations["list_jobs_api_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/rejected": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rejected */
        get: operations["list_rejected_api_jobs_rejected_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Stats */
        get: operations["get_stats_api_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{content_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__content_hash__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{content_hash}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Update Status
         * @description Sets application_status, and applied_at the first time a job is
         *     marked "applied". This records that the human applied; it never applies
         *     on their behalf - there is no code path from here to an employer.
         */
        post: operations["update_status_api_jobs__content_hash__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Run
         * @description Starts the orchestrator in a background thread.
         *
         *     One at a time: a second call while a run is active returns the running
         *     run's id with already_running=True rather than starting a concurrent
         *     one. Two orchestrators would double-spend the same Gemini free-tier
         *     quota and interleave writes to the same SQLite database.
         *
         *     An optional body.thread_id forces a fresh graph thread - see
         *     RunStartRequest for why that escape hatch has to exist.
         */
        post: operations["start_run_api_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Status */
        get: operations["get_run_status_api_run_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/run/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Run */
        get: operations["stream_run_api_run_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resume */
        get: operations["get_resume_api_resume_get"];
        put?: never;
        /**
         * Preview Resume
         * @description Accepts a PDF upload or pasted text. Saves nothing.
         */
        post: operations["preview_resume_api_resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/resume/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Resume */
        post: operations["confirm_resume_api_resume_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_api_preferences_get"];
        /** Update Preferences */
        put: operations["update_preferences_api_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Preferences
         * @description Impact without saving. Runs the same filter pass the pipeline would,
         *     against the candidate lists, leaving config.* untouched.
         */
        post: operations["preview_preferences_api_preferences_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preferences/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Preferences */
        post: operations["reset_preferences_api_preferences_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Companies */
        get: operations["list_companies_api_companies_get"];
        put?: never;
        /**
         * Add Company
         * @description Appends to companies.yaml.
         *
         *     Written with yaml.safe_dump over the parsed list rather than appending
         *     a hand-built string, so a company name containing a colon or a quote
         *     can't produce a file that no longer parses - the same reasoning
         *     agents/scout.py's _found_as_yaml already applies.
         */
        post: operations["add_company_api_companies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/companies/scout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Scout
         * @description Runs the Scout agent against one company name.
         *
         *     Blocking and potentially slow - Scout probes up to MAX_TOTAL_ATTEMPTS
         *     board endpoints and may consult the LLM once when mechanical candidates
         *     are exhausted. Kept synchronous rather than pushed through the run
         *     manager because it's bounded, single-company, and the caller wants the
         *     answer, not a stream. Writes nothing.
         */
        post: operations["run_scout_api_companies_scout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/skill-gaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Skill Gaps */
        get: operations["skill_gaps_api_coach_skill_gaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coach/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask
         * @description A market-gap question, answered over retrieved JDs.
         *
         *     Spends one LLM call. Imports agents.coach's market_gap and the LLM
         *     client lazily so that merely importing the API doesn't pull the RAG
         *     stack (which reaches ranking.py, and through it sentence-transformers)
         *     into every process that serves a job list.
         */
        post: operations["ask_api_coach_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run History
         * @description Recorded runs, most recent first, each with its per-stage metrics.
         *
         *     Only runs started through this API appear here - a CLI run spends the
         *     same quota but writes no metrics row (see /runtime's caveats), so this
         *     is a history of API-triggered runs, not of every run that happened.
         */
        get: operations["run_history_api_meta_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent Metrics
         * @description Per-stage metrics from the most recent recorded run.
         */
        get: operations["agent_metrics_api_meta_agents_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation */
        get: operations["evaluation_api_meta_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/architecture": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Architecture
         * @description A structured description of the pipeline, for the frontend to render
         *     as a diagram. Static by nature - this describes the system's design, not
         *     its runtime state, and hardcoding it here rather than in the React app
         *     keeps one source of truth for what the pipeline actually is.
         */
        get: operations["architecture_api_meta_architecture_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta/runtime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Runtime */
        get: operations["runtime_api_meta_runtime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddCompanyRequest */
        AddCompanyRequest: {
            /** Name */
            name: string;
            /** Ats */
            ats: string;
            /** Token */
            token: string;
            /** Notes */
            notes?: string | null;
        };
        /** AddCompanyResponse */
        AddCompanyResponse: {
            /** Added */
            added: boolean;
            company: components["schemas"]["CompanyStats"];
            /** Total Companies */
            total_companies: number;
        };
        /**
         * AgentMetric
         * @description Per-stage metrics from one run.
         *
         *     `agent` is null for fetch/filter - they're pipeline stages, not agents.
         *     Only the Analyst runs in the nightly path; Scout is on-demand (recorded
         *     separately, see /api/companies/scout) and Coach is weekly. Labelling a
         *     fetch stage with an agent name would misrepresent what ran.
         *
         *     `retries` is null, not 0, when unmeasured. LangGraph's RetryPolicy
         *     retries a node silently - nothing observable fires - so reporting 0
         *     would be a confident claim that no retry happened when the truth is
         *     that nobody counted. Null means "not measured".
         */
        AgentMetric: {
            /** Stage */
            stage: string;
            /** Agent */
            agent?: string | null;
            /** Model */
            model?: string | null;
            /** Companies Checked */
            companies_checked?: number | null;
            /** Jobs Retrieved */
            jobs_retrieved?: number | null;
            /** Jobs Processed */
            jobs_processed?: number | null;
            /**
             * Llm Calls
             * @default 0
             */
            llm_calls: number;
            /**
             * Cache Hits
             * @default 0
             */
            cache_hits: number;
            /**
             * Cache Misses
             * @default 0
             */
            cache_misses: number;
            /** Cache Hit Rate */
            cache_hit_rate?: number | null;
            /** Retries */
            retries?: number | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
        };
        /** AgentsResponse */
        AgentsResponse: {
            /** Run Id */
            run_id?: string | null;
            /** Status */
            status?: string | null;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Trigger */
            trigger?: string | null;
            /** Stages */
            stages?: components["schemas"]["AgentMetric"][];
            /** Notes */
            notes?: string[];
        };
        /** ArchitectureAgent */
        ArchitectureAgent: {
            /** Name */
            name: string;
            /** Decision */
            decision: string;
            /** Description */
            description: string;
            /** Module */
            module: string;
            /** Runs In Nightly Pipeline */
            runs_in_nightly_pipeline: boolean;
        };
        /** ArchitectureEdge */
        ArchitectureEdge: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Label */
            label?: string | null;
        };
        /**
         * ArchitectureResponse
         * @description Structured enough for a frontend to render a diagram without
         *     hardcoding the pipeline shape in the React app.
         */
        ArchitectureResponse: {
            /** Stages */
            stages: components["schemas"]["ArchitectureStage"][];
            /** Agents */
            agents: components["schemas"]["ArchitectureAgent"][];
            /** Edges */
            edges: components["schemas"]["ArchitectureEdge"][];
            /** Principles */
            principles: string[];
        };
        /** ArchitectureStage */
        ArchitectureStage: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Uses Llm */
            uses_llm: boolean;
            /** Module */
            module: string;
        };
        /** AskRequest */
        AskRequest: {
            /** Question */
            question: string;
            /**
             * K
             * @default 12
             */
            k: number;
        };
        /**
         * AskResponse
         * @description A Coach answer plus what it actually retrieved. The retrieved set is
         *     returned alongside the answer, not hidden, so the answer can be checked
         *     against its own evidence rather than taken on trust - the whole point of
         *     RAG over a chatbot.
         *
         *     `retrieval_was_noop` is surfaced, not buried: at this project's current
         *     corpus size, k frequently exceeds the matching pool, meaning "retrieval"
         *     returned everything and ranked nothing. An answer built that way is
         *     still useful, but calling it retrieval-augmented would overstate what
         *     happened. See rag.RetrievalResult.is_noop.
         */
        AskResponse: {
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** K */
            k: number;
            /** Retrieved */
            retrieved?: components["schemas"]["RetrievedChunk"][];
            /** Pool Size */
            pool_size: number;
            /** Retrieved Count */
            retrieved_count: number;
            /** Retrieval Was Noop */
            retrieval_was_noop: boolean;
            /** Population Size */
            population_size: number;
        };
        /** Body_preview_resume_api_resume_post */
        Body_preview_resume_api_resume_post: {
            /** File */
            file?: string | null;
            /** Text */
            text?: string | null;
        };
        /** CompaniesResponse */
        CompaniesResponse: {
            /** Companies */
            companies: components["schemas"]["CompanyStats"][];
            /** Zero Survivor Companies */
            zero_survivor_companies: string[];
        };
        /**
         * CompanyStats
         * @description One companies.yaml entry plus what it actually contributed.
         *     fetched > 0 with survivors == 0 means the company is costing a nightly
         *     fetch and returning nothing usable - a removal candidate.
         */
        CompanyStats: {
            /** Name */
            name: string;
            /** Ats */
            ats: string;
            /** Token */
            token?: string | null;
            /** Jobs Fetched */
            jobs_fetched: number;
            /** Survivors */
            survivors: number;
        };
        /**
         * EvaluationResponse
         * @description Measured ranking quality against the hand-labeled set.
         *
         *     Served from a precomputed snapshot (data/evaluation_results.json,
         *     regenerated by `python evaluate_stage1.py --json`) rather than computed
         *     per request: computing it imports sentence-transformers/torch and
         *     re-embeds every overlap job, which would make one endpoint responsible
         *     for hundreds of megabytes of process memory and a ~15s first call.
         *
         *     `available=False` means the snapshot hasn't been generated yet - an
         *     honest empty state, not zeros that would read as measured results.
         */
        EvaluationResponse: {
            /** Available */
            available: boolean;
            /** Generated At */
            generated_at?: string | null;
            /**
             * N
             * @default 0
             */
            n: number;
            /**
             * Total Labels
             * @default 0
             */
            total_labels: number;
            /** Label Counts */
            label_counts?: {
                [key: string]: number;
            };
            /** Overlap Counts */
            overlap_counts?: {
                [key: string]: number;
            };
            /**
             * Is Minority Of Label Set
             * @default false
             */
            is_minority_of_label_set: boolean;
            /** Mrr */
            mrr?: {
                [key: string]: number;
            };
            /** Recall At 10 */
            recall_at_10?: {
                [key: string]: number;
            };
            /** Recall At 20 */
            recall_at_20?: {
                [key: string]: number;
            };
            /** Good Positions */
            good_positions?: components["schemas"]["GoodJobPosition"][];
            /** Top Stage1 Fit Score */
            top_stage1_fit_score?: number | null;
            /** Top Stage1 Company */
            top_stage1_company?: string | null;
            /** Top Stage1 Title */
            top_stage1_title?: string | null;
            /** Top Stage1 Label */
            top_stage1_label?: string | null;
            /** Caveats */
            caveats?: string[];
        };
        /** GoodJobPosition */
        GoodJobPosition: {
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Embedding Position */
            embedding_position: number;
            /** Stage1 Position */
            stage1_position: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** JobDetail */
        JobDetail: {
            /** Content Hash */
            content_hash: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Url */
            url: string;
            /** Remote Type */
            remote_type: string;
            /** Fit Score */
            fit_score?: number | null;
            /** Verdict */
            verdict: string;
            /** Is Unscored */
            is_unscored: boolean;
            /**
             * Is Promoted Unscored
             * @default false
             */
            is_promoted_unscored: boolean;
            /** Matched Skills */
            matched_skills?: string[];
            /** Missing Skills */
            missing_skills?: string[];
            /** Reasoning */
            reasoning: string;
            /** Model */
            model: string;
            /** Years Required */
            years_required?: number | null;
            /** Resume Meets Experience */
            resume_meets_experience: boolean;
            /** Application Status */
            application_status: string;
            /** Applied At */
            applied_at?: string | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Is New */
            is_new: boolean;
            /** Description */
            description: string;
        };
        /**
         * JobSummary
         * @description One ranked survivor. No description - see JobDetail. fit_score and
         *     verdict are Optional because an "unscored" job (no concrete technical
         *     requirements in the posting, see agents/analyst.py's is_unscored) has
         *     no real score, and serving a 0 or a 50 there would be inventing a
         *     judgment the Analyst explicitly declined to make. is_unscored says
         *     which case a null is.
         */
        JobSummary: {
            /** Content Hash */
            content_hash: string;
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Url */
            url: string;
            /** Remote Type */
            remote_type: string;
            /** Fit Score */
            fit_score?: number | null;
            /** Verdict */
            verdict: string;
            /** Is Unscored */
            is_unscored: boolean;
            /**
             * Is Promoted Unscored
             * @default false
             */
            is_promoted_unscored: boolean;
            /** Matched Skills */
            matched_skills?: string[];
            /** Missing Skills */
            missing_skills?: string[];
            /** Reasoning */
            reasoning: string;
            /** Model */
            model: string;
            /** Years Required */
            years_required?: number | null;
            /** Resume Meets Experience */
            resume_meets_experience: boolean;
            /** Application Status */
            application_status: string;
            /** Applied At */
            applied_at?: string | null;
            /**
             * First Seen
             * Format: date-time
             */
            first_seen: string;
            /** Is New */
            is_new: boolean;
        };
        /**
         * PreferenceLists
         * @description The four editable rule-filter keyword lists. Mirrors
         *     models.Preferences exactly - kept as its own type so the HTTP contract
         *     doesn't silently change shape if the domain model gains an internal
         *     field.
         */
        PreferenceLists: {
            /** Title Allowlist */
            title_allowlist: string[];
            /** Seniority Keywords */
            seniority_keywords: string[];
            /** Non Engineering Keywords */
            non_engineering_keywords: string[];
            /** India Location Keywords */
            india_location_keywords: string[];
        };
        /**
         * PreferencesImpact
         * @description Survivor counts before and after a candidate edit. `unanalyzed_after`
         *     is how many of the new survivors have no Analyst result yet - i.e. how
         *     much a run would actually have to do.
         */
        PreferencesImpact: {
            /** Current Survivors */
            current_survivors: number;
            /** New Survivors */
            new_survivors: number;
            /** Delta */
            delta: number;
            /** Unanalyzed After */
            unanalyzed_after: number;
        };
        /**
         * PreferencesResponse
         * @description `warnings` carries config.load_preferences' fallback notices - an
         *     emptied or unparseable list means the filters are running on built-in
         *     defaults instead of what's on disk, and that has to be visible rather
         *     than silently corrected. An empty title_allowlist in particular would
         *     let every job through and burn a day's LLM quota on unfiltered noise.
         */
        PreferencesResponse: {
            /** Title Allowlist */
            title_allowlist: string[];
            /** Seniority Keywords */
            seniority_keywords: string[];
            /** Non Engineering Keywords */
            non_engineering_keywords: string[];
            /** India Location Keywords */
            india_location_keywords: string[];
            /** Warnings */
            warnings?: string[];
            /**
             * Is Default
             * @default false
             */
            is_default: boolean;
        };
        /** PreferencesUpdateResponse */
        PreferencesUpdateResponse: {
            /** Title Allowlist */
            title_allowlist: string[];
            /** Seniority Keywords */
            seniority_keywords: string[];
            /** Non Engineering Keywords */
            non_engineering_keywords: string[];
            /** India Location Keywords */
            india_location_keywords: string[];
            /** Saved */
            saved: boolean;
            /** Survivors */
            survivors: number;
            /** Unanalyzed */
            unanalyzed: number;
            /** Warnings */
            warnings?: string[];
        };
        /** QuotaModel */
        QuotaModel: {
            /** Model */
            model: string;
            /** Calls Today */
            calls_today: number;
            /** Daily Limit */
            daily_limit?: number | null;
            /** Requests Per Minute */
            requests_per_minute?: number | null;
        };
        /** RejectedJob */
        RejectedJob: {
            /** Company */
            company: string;
            /** Title */
            title: string;
            /** Location */
            location?: string | null;
            /** Reason */
            reason: string;
        };
        /** RejectedPage */
        RejectedPage: {
            /** Items */
            items: components["schemas"]["RejectedJob"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Rules */
            rules: string[];
        };
        /** ResumeConfirmRequest */
        ResumeConfirmRequest: {
            /** Text */
            text: string;
        };
        /** ResumeConfirmResponse */
        ResumeConfirmResponse: {
            /** Saved */
            saved: boolean;
            /** Length */
            length: number;
            /** Invalidated Cached Analyses */
            invalidated_cached_analyses: number;
        };
        /**
         * ResumeExtraction
         * @description What extraction.extract_resume_sections pulled, and whether it
         *     actually recognized headers or fell back.
         *
         *     `extracted=False` means no "Technical Skills"/"Projects" header matched
         *     and the FULL text would be sent to the Analyst instead of a trimmed
         *     section. That's surfaced as its own boolean rather than left implicit,
         *     on the same visible-fallback principle the JD extractor follows: a
         *     silent fallback looks exactly like a successful extraction from the
         *     outside, and would quietly change every score.
         */
        ResumeExtraction: {
            /** Skills */
            skills: string;
            /** Projects */
            projects: string;
            /** Extracted */
            extracted: boolean;
        };
        /**
         * ResumePreview
         * @description A candidate resume, not yet saved. `warnings` are the mangled-PDF
         *     tripwires (unusually long words, low space ratio, big length drop) -
         *     empty means nothing obvious looked wrong, never that extraction is
         *     proven clean.
         *
         *     `invalidates_cached_analyses` is how many currently-analyzed jobs would
         *     need re-scoring if this were saved: the resume text is part of every
         *     Analyst cache key, so changing it doesn't corrupt anything, it just
         *     stops matching - and the next run spends real quota re-analyzing.
         */
        ResumePreview: {
            /** Text */
            text: string;
            /** Length */
            length: number;
            extraction: components["schemas"]["ResumeExtraction"];
            /** Warnings */
            warnings?: string[];
            /** Invalidates Cached Analyses */
            invalidates_cached_analyses: number;
            /** Previous Length */
            previous_length?: number | null;
        };
        /** ResumeResponse */
        ResumeResponse: {
            /** Text */
            text: string;
            /** Length */
            length: number;
            extraction: components["schemas"]["ResumeExtraction"];
            /** Exists */
            exists: boolean;
        };
        /**
         * RetrievedChunk
         * @description One retrieved JD requirements excerpt and its cosine similarity to
         *     the question.
         */
        RetrievedChunk: {
            /** Text */
            text: string;
            /** Score */
            score: number;
        };
        /**
         * RunEvent
         * @description One progress event, as served over SSE and replayed by
         *     /api/run/status. Mirrors pipeline.ProgressEvent plus a sequence number
         *     and timestamp the API adds.
         *
         *     `seq` is monotonic within a run so a client that reconnects can tell
         *     whether it missed anything and in what order things happened - SSE
         *     gives no ordering guarantee across a reconnect on its own.
         *
         *     `agent` is null for fetch/filter on purpose: those are pipeline stages,
         *     not agents. See pipeline.ProgressEvent.agent.
         */
        RunEvent: {
            /** Seq */
            seq: number;
            /**
             * Ts
             * Format: date-time
             */
            ts: string;
            /** Stage */
            stage: string;
            /** Agent */
            agent?: string | null;
            /** Message */
            message: string;
            /** Current */
            current?: number | null;
            /** Total */
            total?: number | null;
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /**
         * RunHistoryEntry
         * @description One recorded run, with its per-stage detail.
         *
         *     Same AgentMetric shape as AgentsResponse.stages - the history view and
         *     the latest-run view render identical rows, so they must not diverge
         *     into two subtly different metric types.
         */
        RunHistoryEntry: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: string | null;
            /** Trigger */
            trigger?: string | null;
            /** Error */
            error?: string | null;
            /** Duration Seconds */
            duration_seconds?: number | null;
            /**
             * Total Llm Calls
             * @default 0
             */
            total_llm_calls: number;
            /** Stages */
            stages?: components["schemas"]["AgentMetric"][];
        };
        /** RunHistoryResponse */
        RunHistoryResponse: {
            /** Runs */
            runs?: components["schemas"]["RunHistoryEntry"][];
            /** Notes */
            notes?: string[];
        };
        /**
         * RunStartRequest
         * @description Optional body for POST /api/run.
         *
         *     thread_id overrides orchestrator.run_nightly's automatic date-based
         *     thread selection. It exists because that automatic selection is
         *     deliberately idempotent: once `nightly-YYYY-MM-DD` has reached END,
         *     re-invoking it resumes a completed graph, which LangGraph correctly
         *     answers by returning the checkpointed final state without executing a
         *     single node. That is the right behaviour for a 2am cron that might
         *     fire twice - but from a UI it looks like "Start run" did nothing, with
         *     an empty timeline and no explanation.
         *
         *     Passing an unused thread_id forces a genuinely fresh run. The UI sends
         *     one only when the user explicitly asks to re-run a day that already
         *     completed, so the ordinary path keeps the crash-resume behaviour the
         *     date-based ids give it.
         */
        RunStartRequest: {
            /** Thread Id */
            thread_id?: string | null;
        };
        /** RunStartResponse */
        RunStartResponse: {
            /** Run Id */
            run_id: string;
            /** Status */
            status: string;
            /**
             * Already Running
             * @default false
             */
            already_running: boolean;
            /**
             * No Op
             * @default false
             */
            no_op: boolean;
            /** Thread Id */
            thread_id?: string | null;
        };
        /**
         * RunStatus
         * @description Everything a client needs to render Mission Control from a cold
         *     connect, without having watched the stream from the beginning.
         *
         *     `events` carries the full replay buffer for the current/last run, so a
         *     browser refresh at job 30 of 41 shows the whole run rather than a blank
         *     pane until the next event happens to fire.
         */
        RunStatus: {
            /** Run Id */
            run_id?: string | null;
            /** Status */
            status: string;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Error */
            error?: string | null;
            /** Current Stage */
            current_stage?: string | null;
            /** Current Agent */
            current_agent?: string | null;
            /** Last Message */
            last_message?: string | null;
            /** Current */
            current?: number | null;
            /** Total */
            total?: number | null;
            /** Events */
            events?: components["schemas"]["RunEvent"][];
        };
        /**
         * RuntimeResponse
         * @description `quota` is derived from run_agent_metrics - i.e. only counts runs
         *     started through this API. A run launched from the CLI
         *     (`python orchestrator.py`) spends the same Gemini quota but writes no
         *     metrics row, so these numbers are a floor, not a ledger. Stated in
         *     `caveats` rather than presented as exact.
         */
        RuntimeResponse: {
            /** Test Count */
            test_count: number;
            /** Db Size Bytes */
            db_size_bytes?: number | null;
            /** Db Backend */
            db_backend: string;
            /** Job Count */
            job_count: number;
            /** Analyst Result Count */
            analyst_result_count: number;
            /** Total Tokens Recorded */
            total_tokens_recorded: number;
            /** Last Successful Run */
            last_successful_run?: string | null;
            /** Quota */
            quota?: components["schemas"]["QuotaModel"][];
            /** Caveats */
            caveats?: string[];
            /** Extra */
            extra?: {
                [key: string]: unknown;
            };
        };
        /** ScoutEmptyBoard */
        ScoutEmptyBoard: {
            /** Token */
            token: string;
            /** Source */
            source: string;
        };
        /** ScoutRequest */
        ScoutRequest: {
            /** Name */
            name: string;
        };
        /**
         * ScoutResponse
         * @description What Scout concluded. `success=False` with a non-empty
         *     `empty_boards` is a distinct, useful outcome from a flat miss: a real
         *     board exists, it just has zero open jobs right now, so it's worth
         *     re-scouting later rather than writing the company off.
         *
         *     Nothing here is written to companies.yaml - POST /api/companies does
         *     that, deliberately as a separate, explicit step.
         */
        ScoutResponse: {
            /** Company Name */
            company_name: string;
            /** Success */
            success: boolean;
            /** Ats */
            ats?: string | null;
            /** Token */
            token?: string | null;
            /** Job Count */
            job_count?: number | null;
            /** Conclusion */
            conclusion: string;
            /** Requests Used */
            requests_used: number;
            /** Empty Boards */
            empty_boards?: components["schemas"]["ScoutEmptyBoard"][];
        };
        /** SkillGap */
        SkillGap: {
            /** Skill */
            skill: string;
            /** Count */
            count: number;
        };
        /**
         * SkillGapsResponse
         * @description Missing-skills frequency across stage-1-scored jobs below a
         *     threshold. Stage-1 only, deliberately: mixing stage-1 and stage-2 rows
         *     would aggregate judgments made by two different models into one count
         *     that means neither. See agents/coach.py.
         */
        SkillGapsResponse: {
            /** Threshold */
            threshold: number;
            /** Job Count */
            job_count: number;
            /** Skills */
            skills?: components["schemas"]["SkillGap"][];
        };
        /**
         * StatsResponse
         * @description The funnel. `pending` is survivors with no Analyst result yet -
         *     surfaced as its own number rather than folded into `analyzed`, because
         *     "the orchestrator hasn't reached it" and "the Analyst looked and had
         *     nothing to compare" are different states with different fixes.
         */
        StatsResponse: {
            /** Total Fetched */
            total_fetched: number;
            /** Survived */
            survived: number;
            /** Analyzed */
            analyzed: number;
            /** Pending */
            pending: number;
            /** Rejected By */
            rejected_by: {
                [key: string]: number;
            };
            /** Last Run */
            last_run?: string | null;
        };
        /** StatusUpdateRequest */
        StatusUpdateRequest: {
            /** Status */
            status: string;
        };
        /** StatusUpdateResponse */
        StatusUpdateResponse: {
            /** Content Hash */
            content_hash: string;
            /** Application Status */
            application_status: string;
            /** Applied At */
            applied_at?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_jobs_api_jobs_get: {
        parameters: {
            query?: {
                /** @description filter by application_status; repeatable */
                status?: string[] | null;
                include_unscored?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rejected_api_jobs_rejected_get: {
        parameters: {
            query?: {
                rule?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RejectedPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_api_stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsResponse"];
                };
            };
        };
    };
    get_job_api_jobs__content_hash__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_status_api_jobs__content_hash__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                content_hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StatusUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatusUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunStartRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStartResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_status_api_run_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
        };
    };
    stream_run_api_run_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_resume_api_resume_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeResponse"];
                };
            };
        };
    };
    preview_resume_api_resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["Body_preview_resume_api_resume_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumePreview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_resume_api_resume_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeConfirmRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumeConfirmResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_api_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesResponse"];
                };
            };
        };
    };
    update_preferences_api_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceLists"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_preferences_api_preferences_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreferenceLists"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesImpact"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_preferences_api_preferences_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreferencesUpdateResponse"];
                };
            };
        };
    };
    list_companies_api_companies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompaniesResponse"];
                };
            };
        };
    };
    add_company_api_companies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCompanyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddCompanyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_scout_api_companies_scout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScoutResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    skill_gaps_api_coach_skill_gaps_get: {
        parameters: {
            query?: {
                threshold?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillGapsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_api_coach_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_history_api_meta_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistoryResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_metrics_api_meta_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentsResponse"];
                };
            };
        };
    };
    evaluation_api_meta_evaluation_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationResponse"];
                };
            };
        };
    };
    architecture_api_meta_architecture_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchitectureResponse"];
                };
            };
        };
    };
    runtime_api_meta_runtime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuntimeResponse"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
