from datetime import datetime
from typing import Any, Optional

from pydantic import BaseModel, Field


class AgentMetric(BaseModel):
    """Per-stage metrics from one run.

    `agent` is null for fetch/filter - they're pipeline stages, not agents.
    Only the Analyst runs in the nightly path; Scout is on-demand (recorded
    separately, see /api/companies/scout) and Coach is weekly. Labelling a
    fetch stage with an agent name would misrepresent what ran.

    `retries` is null, not 0, when unmeasured. LangGraph's RetryPolicy
    retries a node silently - nothing observable fires - so reporting 0
    would be a confident claim that no retry happened when the truth is
    that nobody counted. Null means "not measured"."""

    stage: str
    agent: Optional[str] = None
    model: Optional[str] = None

    companies_checked: Optional[int] = None
    jobs_retrieved: Optional[int] = None
    jobs_processed: Optional[int] = None

    llm_calls: int = 0
    cache_hits: int = 0
    cache_misses: int = 0
    cache_hit_rate: Optional[float] = None  # null when nothing was looked up at all

    retries: Optional[int] = None
    duration_seconds: Optional[float] = None


class AgentsResponse(BaseModel):
    run_id: Optional[str] = None
    status: Optional[str] = None
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    trigger: Optional[str] = None
    stages: list[AgentMetric] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class RunHistoryEntry(BaseModel):
    """One recorded run, with its per-stage detail.

    Same AgentMetric shape as AgentsResponse.stages - the history view and
    the latest-run view render identical rows, so they must not diverge
    into two subtly different metric types."""

    run_id: str
    status: str
    started_at: datetime
    finished_at: Optional[datetime] = None
    trigger: Optional[str] = None
    error: Optional[str] = None
    # Null when a run never finished (crashed, killed, or still going) -
    # not zero, which would read as "took no time".
    duration_seconds: Optional[float] = None
    total_llm_calls: int = 0
    stages: list[AgentMetric] = Field(default_factory=list)


class RunHistoryResponse(BaseModel):
    runs: list[RunHistoryEntry] = Field(default_factory=list)
    notes: list[str] = Field(default_factory=list)


class GoodJobPosition(BaseModel):
    company: str
    title: str
    embedding_position: int
    stage1_position: int


class EvaluationResponse(BaseModel):
    """Measured ranking quality against the hand-labeled set.

    Served from a precomputed snapshot (data/evaluation_results.json,
    regenerated by `python evaluate_stage1.py --json`) rather than computed
    per request: computing it imports sentence-transformers/torch and
    re-embeds every overlap job, which would make one endpoint responsible
    for hundreds of megabytes of process memory and a ~15s first call.

    `available=False` means the snapshot hasn't been generated yet - an
    honest empty state, not zeros that would read as measured results."""

    available: bool
    generated_at: Optional[datetime] = None

    n: int = 0
    total_labels: int = 0
    label_counts: dict[str, int] = Field(default_factory=dict)
    overlap_counts: dict[str, int] = Field(default_factory=dict)
    is_minority_of_label_set: bool = False

    mrr: dict[str, float] = Field(default_factory=dict)
    recall_at_10: dict[str, float] = Field(default_factory=dict)
    recall_at_20: dict[str, float] = Field(default_factory=dict)

    good_positions: list[GoodJobPosition] = Field(default_factory=list)
    top_stage1_fit_score: Optional[int] = None
    top_stage1_company: Optional[str] = None
    top_stage1_title: Optional[str] = None
    top_stage1_label: Optional[str] = None

    caveats: list[str] = Field(default_factory=list)


class ArchitectureStage(BaseModel):
    """One conceptual step. `node` names the LangGraph node it actually runs
    inside - the orchestrator has only three, and fetch/persist/filter are
    deliberately bundled into one (see orchestrator.py's module docstring),
    so a stage list alone would misrepresent the real graph."""

    key: str
    name: str
    description: str
    uses_llm: bool
    module: str
    node: str


class ArchitectureAgent(BaseModel):
    name: str
    decision: str
    description: str
    module: str
    runs_in_nightly_pipeline: bool


class ArchitectureEdge(BaseModel):
    source: str
    target: str
    label: Optional[str] = None


class ArchitectureResponse(BaseModel):
    """Structured enough for a frontend to render a diagram without
    hardcoding the pipeline shape in the React app."""

    stages: list[ArchitectureStage]
    agents: list[ArchitectureAgent]
    edges: list[ArchitectureEdge]
    principles: list[str]
    # The real LangGraph node names, in execution order. Stated separately
    # from `stages` so the graph cannot drift from the prose describing it.
    orchestrator_nodes: list[str] = Field(default_factory=list)
    # Things deliberately NOT in the pipeline, with the reason. Omitting
    # them entirely was how a removed embedding stage stayed on this page
    # long after it stopped running.
    not_in_pipeline: list[str] = Field(default_factory=list)


class QuotaModel(BaseModel):
    model: str
    calls_today: int
    daily_limit: Optional[int] = None
    requests_per_minute: Optional[int] = None


class RuntimeResponse(BaseModel):
    """`quota` is derived from run_agent_metrics - i.e. only counts runs
    started through this API. A run launched from the CLI
    (`python orchestrator.py`) spends the same Gemini quota but writes no
    metrics row, so these numbers are a floor, not a ledger. Stated in
    `caveats` rather than presented as exact."""

    test_count: int
    # None on Postgres - there is no local database file to stat, and "not
    # measured from here" is a different fact from a size of zero. The
    # frontend renders null as "not measured", never as "0 B".
    db_size_bytes: Optional[int] = None
    # "postgresql" or "sqlite", read off the live connection. Replaces the
    # old db_path, which was a local filesystem path: meaningless once
    # deployed, and the obvious "fix" of substituting DATABASE_URL would
    # publish the database password through an unauthenticated endpoint.
    db_backend: str
    job_count: int
    analyst_result_count: int
    total_tokens_recorded: int
    # When the most recent successfully-completed run finished. None means
    # no run has ever completed - not "just now", and not the epoch.
    last_successful_run: Optional[datetime] = None
    quota: list[QuotaModel] = Field(default_factory=list)
    caveats: list[str] = Field(default_factory=list)
    extra: dict[str, Any] = Field(default_factory=dict)
